# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dr. Mindy Curry ND
email: info@passionforhealingnaturopathic.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  In this area Dr. Curry periodically shares her ideas, natural medicine research reviews, recipes, inspirational health stories, health tips, and provides answers to questions her patients are currently asking. These articles are not meant to diagnose or treat any specific condition without Doctor supervision.
  Please call Dr. Curry at 503-995-8674 to schedule a Naturopathic Home Visit when you are ready to address your individual health concerns. Dr. Curry will custom tailor a plan targeted to your individual preferences and goals to optimize your whole body, mind and spirit.
baseurl: "/pfh_blog" # the subpath of your site, e.g. /blog
url: "http://passionforhealingnaturopathic.com" # the base hostname & protocol for your site
twitter_username: drmindycurry
github_username:  jekyll

# Build settings
markdown: kramdown
